# Generated by Django 4.2.3 on 2023-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_remove_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
